[build]
  publish = "dist"
  command = "npm install && npm run build"

[build.environment]
  dgEnableSearch = "true"
  dgShowFileTree = "true"
  dgShowToc = "true"
  dgShowBacklinks = "true"
  dgShowLocalGraph = "true"
  dgLinkPreview = "true"
  dgShowTags = "true"
  dgShowInlineTitle = "true"
  dgHomeLink = "true"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404
